### ISSUE TITLE
링크가 내부용으로 되어있습니다.

### ISSUE THREAD

**Issue by apple77y** [nhnent/fe.javascript#10]
안녕하세요.

https://github.com/nhnent/fe.javascript/wiki/jquery-가이드#설치하기
해당 링크의 참고 부분은 내부 OSS에 있는 아티클에 걸려있어서 접근이 안 됩니다.
수정해주시면 감사하겠습니다.

FE Weekly를 통해 유익한 정보를 주셔서 감사합니다.
꾸준히 구독중입니다 :)

**Comment by junghwan-park** [comment]
안녕하세요 NHN Entertainment FE개발랩입니다.

해당 링크 수정 완료 했습니다. 다른 페이지도 링크가 잘 달려있는지 확인 해보겠습니다. :)

저희 개발 가이드에 많은 관심을 주셔서 감사합니다.
