### ISSUE TITLE
weekly june-13 내용 관련

### ISSUE THREAD

**Issue by cs09g** [nhnent/fe.javascript#11]
[단일 호출 스택과 Run-to-Completion](https://github.com/nhnent/fe.javascript/wiki/June-13-June-17,-2016#%EB%8B%A8%EC%9D%BC-%ED%98%B8%EC%B6%9C-%EC%8A%A4%ED%83%9D%EA%B3%BC-run-to-completion)

실행 순서에 오타가 나신 건지,
bar -> foo -> baz 같아요..

**Comment by dongwoo-kim** [comment]
아... 순서를 잘못 적었네요. 수정했습니다. 감사합니다 :)

**Comment by cs09g** [comment]
https://github.com/nhnent/fe.javascript/wiki/FE-Weekly 요기 목록에서 스펠링 에러
Jone -> June 도 있네요ㅋ

**Comment by dongwoo-kim** [comment]
어이쿠.. 그러네요 ㅎㅎ 감사합니다.
