### ISSUE TITLE
오타를 찾았습니다.

### ISSUE THREAD

**Issue by apple77y** [nhnent/fe.javascript#13]
[오타가 난 부분](https://github.com/nhnent/fe.javascript/wiki/June-13-June-17,-2016#태스크-큐와-이벤트-루프)
* 태스트 큐 -> 태스크 큐

자바스크립트가 싱글 스레드 기반인데 비동기 처리를 내부적으로 어떻게 하는지에 대해, 몇 개월 동안 자료를 뒤적여봐도 와닿는 자료를 못봤었는데 이번 아티클로 많이 배웠습니다. 감사합니다 👍

**Comment by dongwoo-kim** [comment]
제보 감사드립니다. 오타 확인해서 수정했습니다. 
부족한 글인데 도움이 되었다니 기쁘네요 ㅎㅎ 저희 팀에서 자바스크립트 관련 좋은 내용 있으면 꾸준히 공유하고 있으니  많은 관심 부탁드리겠습니다!
