### ISSUE TITLE
오타 

### ISSUE THREAD

**Issue by cs09g** [nhnent/fe.javascript#17]
https://github.com/nhnent/fe.javascript/wiki/August-15-August-19,-2016#%EA%B2%B0%EB%A1%A0

링크에서 첫 번째 하얀 동그라미의
예를 들어 ~~ 항목에서 '정적 프론테 엔드' -> '정적 프론트 엔드'

**Comment by minkyu-yi** [comment]
수정하였습니다~~ 감사합니다.
