### ISSUE TITLE
위키 문서 오타

### ISSUE THREAD

**Issue by cs09g** [nhnent/fe.javascript#20]
1. setTImeout -> setTimeout

https://github.com/nhnent/fe.javascript/wiki/%EA%B8%B0%EC%88%A0-%EC%9E%90%EB%A3%8C#settimeout%EA%B3%BC-setinterval

2. 
[Webkt 엔진] -> [Webkit 엔진]
disply:none; -> display:none;
최적하 기법 -> 최적화 기법
Refolw -> Reflow

https://github.com/nhnent/fe.javascript/wiki/Reflow%EC%99%80-Repaint

**Comment by junghwan-park** [comment]
안녕하세요, FE개발랩 박정환입니다.
말씀해주신 문서의 잘못 적힌 부분들을 수정해서 반영했습니다.

저희 문서에 관심가져주셔서 감사합니다. 좋은하루 되세요~  :)

**Comment by cs09g** [comment]
네~ 수고하세요~
