### ISSUE TITLE
FE Weekly 문서 내용 중 샘플코드 오류

### ISSUE THREAD

**Issue by pistos2** [nhnent/fe.javascript#26]
August 03 — August 07, 2015
13.2   파생클래스(Derived classes) 섹션에서 
"ES6는 extends 절을 통해 내장된 서브클래싱을 지원한다." 부분의 샘플 코드가 잘못 들어간 것 같습니다. 

https://github.com/nhnent/fe.javascript/wiki/August-03-%E2%80%94-August-07,-2015

**Comment by junghwan-park** [comment]
안녕하세요 FE개발랩 박정환입니다.

알려주신 문서의 예제 코드가 잘못 삽입되어 있는 것 확인해서 수정 완료했습니다.
소중한 제보 감사합니다.

그리고 저희 Weekly Pick에 관심을 가져주셔서 감사합니다. 좋은하루 되세요~ :)
