### ISSUE TITLE
위키 문서 오타입니다.

### ISSUE THREAD

**Issue by cnaa97** [nhnent/fe.javascript#27]
(https://github.com/nhnent/fe.javascript/wiki/March-27---March-31,-2017#3%EA%B0%80%EC%A7%80-%EC%9B%90%EC%B9%99)[리덕스 분석하기] 위키에서 

3가지 원칙 중

Changes from `fure` functions -> Changes from `pure` functions 을 잘못 쓰신 것 같습니다.
pure가 맞습니다.

감사합니다.

**Comment by junghwan-park** [comment]
안녕하세요 FE개발랩 박정환입니다.

알려주신 문서의 오타를 확인하고 바로 수정 적용되었습니다.
감사합니다. =)
