### ISSUE TITLE
오타를 찾았습니다.

### ISSUE THREAD

**Issue by apple77y** [nhnent/fe.javascript#29]
``` CommontJS 포맷 ```에서 ``` CommonJS 포맷 ```로 수정 되어야 합니다.

위치: https://github.com/nhnent/fe.javascript/wiki/April-10---April-14,-2017#commontjs-%ED%8F%AC%EB%A7%B7

**Comment by junghwan-park** [comment]
안녕하세요 FE개발랩 박정환입니다.

소중한 제보 감사합니다.
알려주신 오타는 바로 수정되었습니다.

감사합니다. :)
