### ISSUE TITLE
오타 제보합니다

### ISSUE THREAD

**Issue by seongahjo** [nhnent/fe.javascript#32]
1.

`## RequireJS [RequireJS](http://requirejs.org/)는 AMD 방식의 대표적인 자바스크립트 모듈 관리 라이브러리이다.`
태그가 제대로 적용이 안되있는 것 같습니다

위치 : 
https://github.com/nhnent/fe.javascript/wiki/%EC%9D%98%EC%A1%B4%EC%84%B1-%EA%B4%80%EB%A6%AC

2.
`## 목차 * [ECMAScript6](#ecmascript6) * [DTD](#dtd) * [박스모델](#박스모델) * [Reflow와 Repaint](#reflow와-repaint) * [setTimeout과 setInterval](#settimeout과-setinterval)`

위치 :
https://github.com/nhnent/fe.javascript/wiki/%EA%B8%B0%EC%88%A0-%EC%9E%90%EB%A3%8C

**Comment by seonim-ryu** [comment]
@seongahjo
안녕하세요. 제보주신 부분은 수정하여 반영해두었습니다.
앞으로도 적극적인 관심 부탁드립니다. :)
