### ISSUE TITLE
오타 제보

### ISSUE THREAD

**Issue by cs09g** [nhnent/fe.javascript#34]
https://github.com/nhnent/fe.javascript/wiki/November-27---December-1%2C-2017#네트워크
내용 중
>* 크게 압축한다. (Brotli~q11, Zopfli 또는 gzip 사용) Brotil는 gzip보다 압축률이 좋다.

Brotil => Brotli

**Comment by seonim-ryu** [comment]
@cs09g 
제보 감사합니다. 수정하여 반영해두었고요.
앞으로도 많은 관심 부탁드립니다. :)
