### ISSUE TITLE
오역 제보 

### ISSUE THREAD

**Issue by jiyeonseo** [nhnent/fe.javascript#40]
글 너무 즐겁게 읽고 있습니다! 항상 감사합니다! 

올려주신 [틴더 케이스 스터디](https://github.com/nhnent/fe.javascript/wiki/%23169:-Tinder%EC%9D%98-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EC%8B%9C%EB%B8%8C-%EC%9B%B9-%EC%95%B1-%EC%84%B1%EB%8A%A5-%EC%BC%80%EC%9D%B4%EC%8A%A4-%EC%8A%A4%ED%84%B0%EB%94%94 )에서 

> Users swipe more on web than their native apps

의 번역이 

> 사용자는 네이티브 앱보다 웹에서 이성을 더 많이 선택한다.

로 되어있는데,  

틴더 앱의 특성상 이성 선택으로 의역이 가능한것 같지만 
해당 글 문맥에서는 "Swipe" 유저 액션이 늘어났다는 이야기 같습니다. 

혹시나 제가 잘못 이해한거면 다시 알려주세요 ^^; 
감사합니다!!

**Comment by kyuwoo-choi** [comment]
@jiyeonseo 제보 감사합니다. 😉 

틴더 앱에서 _swipe_ = _이성 선택_ 이므로 둘 다 맞는 말이라고 생각됩니다.
다만 아래 문장들을 보면, _메세지를 많이 보낸다_, _구매 한다_ 등으로 유저 관점에서 동작으로 기술했기 때문에, 현재 _이성을 더 많이 선택한다_ 쪽이 더 어울리지 않나 생각 합니다.

**Comment by jiyeonseo** [comment]
답변 감사합니다 :-) 
이슈는 제가 닫을께요! 😉
(제가 좋아요 남기면서 코멘트 남겼다고 생각햇는데 안되어 있었네요 ㅠㅜ )
