### ISSUE TITLE
weekly #188 오탈자 제보

### ISSUE THREAD

**Issue by armadillo-dev** [nhnent/fe.javascript#41]
매주 올라오는 FE weekly 잘 보고 있습니다 :-)

https://github.com/nhnent/fe.javascript/wiki/%EB%B0%94%EB%B2%A8%EA%B3%BC-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%EC%9D%98-%EC%95%84%EB%A6%84%EB%8B%A4%EC%9A%B4-%EA%B2%B0%ED%98%BC

내용의 가장 마지막 부분에 오타가 있어 제보 드립니다.

**현재** 타입스크립트가 설치하기 _어려우서_ 미루고 있었다면, 이제 더 이상 미룰 이유가 없다.
**수정** 타입스크립트가 설치하기 _어려워서_ 미루고 있었다면, 이제 더 이상 미룰 이유가 없다.

**Comment by dongsik-yoo** [comment]
제보 감사합니다. 
말씀하신 부분 수정이 되어서 이슈 클로즈하겠습니다.
