### ISSUE TITLE
Copyright Infringement

### ISSUE THREAD

**Issue by indysigner** [nhnent/fe.javascript#43]
Please take down the article published at https://github.com/nhnent/fe.javascript/wiki/%23193:-CSS%EB%A5%BC-%EB%B0%B0%EC%9A%B0%EB%8A%94-%EB%B0%A9%EB%B2%95

This has been published without our permission, we have another Korean company pay for the article translation license. 

Copying and pasting may save you a lot of time and bring you some traffic, however you won't be able to build up a reputation on the web. Stolen content can be noticed very quickly and the “author” of the post will consequently be marked as a thief. Therefore, if you've found an interesting post on Smashing Magazine or somewhere else, please don't copy it. Instead, quote it or publish an excerpt with a visible link plus a canonical link to the original source.

Get creative by the works of other people, but respect their work, their time and their willingness to give the information to you—for free. You’d want to be paid for your work? Cool, so do we, and if you don’t have purchased a content license from us, it’s stealing.

We urge you to remove this and any other posts you've copied from our website and have posted on your site. If we don't get any response from you, we'll contact your hosting provider inform them about the copyright infringement — you may be aware of the negative consequences this can lead for you.

Looking forward to hearing from you.

— Markus Seyfferth

**Comment by shiren** [comment]
First of all, We are so sorry about that.
You are right. we should get permission before we publish translated post.
We had no purpose other than to share good article.
We have closed wiki page. then we will open it someday with original post & licensed post.
Thanks.

**Comment by indysigner** [comment]
No worries, I figured that! :-)

You can find the article over at the https://webactually.com/post_magazine/smashing-magazine/ site. :-)

All the best,

—  Markus

**Comment by shiren** [comment]
The site will be very helpful. Thanks :)
