### ISSUE TITLE
wiki 재오픈 계획에 관한 문의

### ISSUE THREAD

**Issue by ndotcom** [nhnent/fe.javascript#44]
그동안 올려주셨던 번역본 덕분에 은혜입으며 살아왔었습니다. 

이제 제 힘으로 일어서야 할 때 일까요?
사실 이렇게 팀 공유용 자료를 공개해 주시는 것도 쉬운 일은 아닐텐데 공짜로 도움 받아놓고 감사하다는 말씀을 그동안 못드렸던 것 같습니다.
덕분에 많은 도움되었었습니다. 리스펙합니다.

일도 많아 바쁘신데 라이센스 하나하나 따져가며 공개여부를 정하실 일은 없을거라 추측하고 있으니, 재오픈은 사실 기대하지는 않고 있습니다.

그래도 언젠가 다시 열린다면 정말 뛸 듯이 기쁠 것도 같습니다.
엔터 FE개발랩 여러분 모두 만수무강 하세요.

**Comment by shiren** [comment]
우선 아닙니다.
일일이 라이센스 하나하나 따져가며 공개 여부를 정해서 공개할 예정입니다 :)
그러니 걱정 마세요. 조만간 재오픈 할 예정입니다 :)
번역 작업은 계속 진행되고 있으며 사외 오픈을 하지 않을 뿐 사내 공유는 계속되고 있습니다.

그리고 작성자와 구독자의 편의를 위해 깃헙 fe.javascript 리포의 위키를 통해 공개되던 위클리픽 외 모든 기술 공유 작업은 [TOAST UI 공식사이트](https://ui.toast.com) 에 통합될 예정입니다. (2019년 2q 목표)

2019년에도 FE개발랩의 기술공유는 계속될 뿐 아니라 더 확대될 예정입니다!

**Comment by shiren** [comment]
@ndotcom 내용 확인후 직접 close 부탁드립니다.

**Comment by ndotcom** [comment]
@shiren 감사합니다. 항상 응원하겠습니다!!

**Comment by adhrinae** [comment]
@ndotcom 라이센스 하나하나 따져가며 공개 여부를 정할 일이 없다는 말씀이 굉장히 위험하게 들립니다

**Comment by apple77y** [comment]
위키가 다시 열렸는지 자주 들락날락 하고 있습니다!_!
응원합니다
