### ISSUE TITLE
오류 수정 요청 드려요..

### ISSUE THREAD

**Issue by nundefined** [nhnent/fe.javascript#5]
1. [시작하기](https://github.com/nhnent/fe.javascript/wiki/시작하기) 페이지에서
영역 하단의 이미지가 노출되지 않습니다. 파일이 없는듯 합니다.

1. [코딩컨벤션](https://github.com/nhnent/fe.javascript/wiki/코딩-컨벤션) 페이지에 포함된
대부분의 참고의 링크가 https://github.nhnent.com 으로 되어 있어요.

처음 프로젝트/팀 셋업할 때 반드시 참고해야 할 좋은 내용이네요~

**Comment by minkyu-yi** [comment]
2번 링크 우선 수정 했습니다~ 감사합니다

**Comment by minkyu-yi** [comment]
1번 - 시작하기 페이지의 brackets 이미지 수정하였습니다.
감사합니다.

https://github.com/nhnent/fe.javascript/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0#brackets
