### ISSUE TITLE
이미지가 표시되지않는 두 부분 보고!

### ISSUE THREAD

**Issue by GichanLee** [nhnent/fe.javascript#6]
시작하기

'보통은 아래 그림과 같이 외부 코드를 lib와 같은 이름으로 별도의 폴더를 생성하여 관리한다.'
이 문장 바로 밑의 이미지가 보이지 않아요(directory라고 쓰여져있네요)

'Bracket' 에디터를 설명하는 부분에 Bracket 캡쳐라고 예상되는 부분의 이미지가 보이지않아요. 2016 03 26...으로 적혀있네요.

**Comment by minkyu-yi** [comment]
감사합니다~ 이미지 수정하였습니다.

**Comment by minkyu-yi** [comment]
lib관련 문구 수정
https://github.com/nhnent/fe.javascript/wiki/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0#%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4%EB%82%98-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC-%EA%B0%99%EC%9D%80-%EC%99%B8%EB%B6%80-%EC%BD%94%EB%93%9C%EB%A5%BC-%EB%82%B4%EB%B6%80-%EA%B0%9C%EB%B0%9C-%EC%BD%94%EB%93%9C%EC%99%80-%EB%B6%84%EB%A6%AC%ED%95%98%EA%B3%A0-%EA%B0%81%EA%B0%81%EC%9D%98-%ED%8F%B4%EB%8D%94%EC%97%90%EC%84%9C-%EA%B4%80%EB%A6%AC%ED%95%9C%EB%8B%A4
