### ISSUE TITLE
안티패턴 예시 관련

### ISSUE THREAD

**Issue by cs09g** [nhnent/fe.javascript#8]
좋은 가이드 작성해 주셔서 감사합니다.
안티패턴 문서를 보다가 예시가 조금 이상해서 문의드려요.

https://github.com/nhnent/fe.javascript/wiki/%EC%95%88%ED%8B%B0-%ED%8C%A8%ED%84%B4#%EC%88%9C%ED%99%98%EB%AC%B8%EC%97%90%EC%84%9C-continue%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EB%A7%88%EB%9D%BC

continue 는 기능 자체가 순환문을 빠져나가는게 아니라 블록 내부에서 continue 다음에 오는 명령을 수행하지 않는 것인데, '순환문을 빠져나갈 의도' 라는 문구가 continue 와 어울리지 않는 것 같습니다.
예시 코드 또한 [Bad] 코드가 순환문을 빠져나가는 것과 무관해 보입니다.

**Comment by junghwan-park** [comment]
안녕하세요 NHN Entertainment FE개발랩입니다.

문의하신 단락의 설명과 예시가 적절하지 않다고 판단하여, 본문 내용과 예제 코드를 수정했습니다.
수정후의 내용은 continue 사용 시 발생할 수 있는 성능 문제와 유지 보수성에 초점을 맞추었습니다.

저희 개발 가이드에 많은 관심을 주셔서 감사합니다.
