### ISSUE TITLE
테스팅에서 오타

### ISSUE THREAD

**Issue by cs09g** [nhnent/fe.javascript#9]
https://github.com/nhnent/fe.javascript/wiki/%ED%85%8C%EC%8A%A4%ED%8C%85#karma-test-runner

에서 Karma 로 이동하는 링크 문자가 Karama 라고 잘못적혀있습니다.

**Comment by cs09g** [comment]
https://github.com/nhnent/fe.javascript/wiki/%ED%85%8C%EC%8A%A4%ED%8C%85#2-jasmine-%ED%94%8C%EB%9F%AC%EA%B7%B8%EC%9D%B8-%EC%84%A4%EC%B9%98 
하위에도 오타 있습니다. 커맨트 -> 커맨드

**Comment by minhyeong-kim** [comment]
안녕하세요 NHN Entertainment FE개발랩입니다.

알려주신 오타들은 수정했고요. 지적하신 부분 외에도 수정할 부분이 있는지 전체적으로 한번 검토하겠습니다.

저희 개발 가이드에 관심 가져주셔서 고맙습니다.
